# Generated by Django 6.0 on 2025-12-22 06:52

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("管理员", "管理员"), ("普通用户", "普通用户")],
                        default="普通用户",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("正常", "正常"), ("冻结", "冻结")],
                        default="正常",
                        max_length=10,
                    ),
                ),
                ("register_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("collect_id", models.AutoField(primary_key=True, serialize=False)),
                ("collect_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "collections",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("complaint_id", models.AutoField(primary_key=True, serialize=False)),
                ("complaint_type", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("待处理", "待处理"), ("已处理", "已处理")],
                        default="待处理",
                        max_length=10,
                    ),
                ),
                ("complaint_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "complaints",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintHandle",
            fields=[
                ("handle_id", models.AutoField(primary_key=True, serialize=False)),
                ("opinion", models.TextField()),
                ("handle_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "complaint_handles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待支付", "待支付"),
                            ("已支付", "已支付"),
                            ("已完成", "已完成"),
                            ("已取消", "已取消"),
                        ],
                        default="待支付",
                        max_length=10,
                    ),
                ),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("pay_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "order_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                ("origin_id", models.AutoField(primary_key=True, serialize=False)),
                ("origin_name", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "origins",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "shopping_carts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                ("specialty_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_start_time", models.DateField()),
                ("sale_end_time", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("上架", "上架"), ("下架", "下架")],
                        default="上架",
                        max_length=10,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "specialties",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ViolationRecord",
            fields=[
                ("violation_id", models.AutoField(primary_key=True, serialize=False)),
                ("violation_type", models.CharField(max_length=100)),
                ("violation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "process_result",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "violation_records",
                "managed": False,
            },
        ),
    ]
