# Generated by Django 6.0 on 2025-12-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
    ]
