# Generated by Django 6.0 on 2025-12-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
